---
title: "Homework 2"
author: "Daniel Acuna"
date: "September 30, 2015"
output: html_document
---

```{r, echo=FALSE}
library(gapminder)
str(gapminder)
install.packages('ggplot2')
library('ggplot2')
```

Plot 1

```{r}
ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp, 
                             colour = continent)) + 
  geom_point(aes(shape = continent))
```

Plot 2

```{r}
ggplot(data = gapminder, aes(x = log(gdpPercap), y = lifeExp,
                             colour = continent)) + 
  geom_point(aes(shape = continent))
```

Plot 3
```{r}
ggplot(data = gapminder, aes(x = log(gdpPercap), y = lifeExp,
                             colour = continent)) + 
  geom_point(aes(shape = continent)) +
  geom_smooth(method = lm,
              se = FALSE)
```
Ugh! Can't fit only one. It's fitting for each continent... 

Plot 4 
```{r}
h <- ggplot(data = gapminder, aes(x = log(gdpPercap), y = lifeExp,
                             colour = continent)) + 
  geom_density(aes(shape = continent))
h + facet_grid(.~cyl)
```

Plot 6

```{r, echo=FALSE}
library(dplyr)
```


```{r}

ggplot(data = gapminder, aes(x = log(gdpPercap), y = lifeExp,
                             colour = continent)) + 
  geom_area()
```